server:
  port: 9310

spring:
  application:
    name: wisepen-search-service
  main:
    allow-bean-definition-overriding: true

  mvc:
    log-request-details: true

  # 1. 连接远程开发环境的 Nacos (获取公共配置和注册服务)
  cloud:
    nacos:
      discovery:
        server-addr: wisepen-dev-server:8848
        username: nacos
        password: oriole003
      config:
        server-addr: wisepen-dev-server:8848
        username: nacos
        password: oriole003
        file-extension: yaml
        group: DEFAULT_GROUP
        shared-configs:
          - data-id: wisepen-common-dev.yaml
            group: DEFAULT_GROUP
            refresh: true

  # 2. 连接本地 Docker 的 Elasticsearch (带 IK 分词器，无密码)
  elasticsearch:
    uris: http://127.0.0.1:9200
    # 因为你的 docker-compose 里写了 xpack.security.enabled=false
    # 所以这里绝对不能写 username 和 password！
    connection-timeout: 5s
    socket-timeout: 30s

# 临时开启追踪日志，查完问题可以删掉
logging:
  level:
    org.springframework.web: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE


