server:
  port: 9310
  tomcat:
    connection-timeout: 60000
    accept-count: 100

spring:
  application:
    name: wisepen-search-service
  main:
    allow-bean-definition-overriding: true

  # =========================================================
  # 🌐 1. 连接远程开发环境的 Nacos
  # =========================================================
  cloud:
    nacos:
      discovery:
        server-addr: wisepen-dev-server:8848
        username: nacos
        password: oriole003
      config:
        server-addr: wisepen-dev-server:8848
        username: nacos
        password: oriole003
        file-extension: yaml
        group: DEFAULT_GROUP
        shared-configs:
          - data-id: wisepen-common-dev.yaml
            group: DEFAULT_GROUP
            refresh: true

    inetutils:
      ignored-interfaces: [VMnet.*, vEthernet.*, docker0]
      preferred-networks: [10]

  # =========================================================
  # 🚀 2. 连接本地 Docker 的 Elasticsearch (带 IK 分词器)
  # =========================================================
  elasticsearch:
    uris: http://127.0.0.1:9200
    connection-timeout: 5s
    socket-timeout: 30s
    # 强制置空，确保不被远程共享配置中的账号密码污染
    username: ""
    password: ""

  # =========================================================
  # 📡 3. 连接远程开发环境的 Kafka
  # =========================================================
 
kafka:
    consumer:
      # 1. 换个没用过的名字，彻底抛弃 608 号的阴影
      group-id: wisepen-search-final-v9 
      # 2. 必须是 latest，表示只看未来，不看过去
      auto-offset-reset: latest
      # 3. 关键：把反序列化器强行换成 String，这样它绝对不会去校验 Header 里的 Type 信息
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        # 移除之前所有的 spring.json 开头的配置，防止干扰
        spring.json.trusted.packages: "*"
# =========================================================
# 📄 4. 远端文档格式转换服务 (指向公共开发服务器)
# =========================================================
jodconverter:
  local:
    enabled: false
  remote:
    enabled: true
    url: http://wisepen-dev-server:8100/

logging:
  level:
    root: INFO
    org.jodconverter: DEBUG
    com.oriole.wisepen.file: INFO
    # 搜索服务追踪日志
    org.springframework.web: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.data.elasticsearch.client.WIRE: TRACE